# Configuration for chart-testing
# See https://github.com/helm/chart-testing#configuration

remote: origin
target-branch: main
chart-dirs:
  - chart
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - stable=https://charts.helm.sh/stable
helm-extra-args: --timeout 600s
validate-maintainers: false
check-version-increment: true
validate-chart-schema: true
validate-yaml: true