site_name: ITL Matrix Synapse Helm Chart
site_description: Documentation for the ITL Matrix Synapse Helm Chart for deploying Matrix homeservers in Kubernetes
site_author: ITlusions
site_url: https://itlusions.github.io/ITL.Matrix.Synapse/

repo_name: ITlusions/ITL.Matrix.Synapse
repo_url: https://github.com/ITlusions/ITL.Matrix.Synapse
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Security: security.md
  - Architecture: architecture.md
  - Deployment: deployment.md
  - Troubleshooting: troubleshooting.md
  - Code Review & Recommendations: recommendations.md

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github
  logo: assets/matrix-logo.svg
  favicon: assets/favicon.ico

plugins:
  - search
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ITlusions/ITL.Matrix.Synapse
    - icon: fontawesome/brands/matrix
      link: https://matrix.org
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

copyright: Copyright &copy; 2024 ITlusions. Licensed under Apache 2.0.