{{- $fullName := include "itl.matrix.synapse.name" . -}}
{{- $namespace := .Release.Namespace -}}
{{- $existingSecret := lookup "v1" "Secret" $namespace (printf "%s-secret" $fullName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  registrationSharedSecret: {{- if $existingSecret }}
    {{ $existingSecret.data.registrationSharedSecret }}
  {{- else }}
    {{ (randAlphaNum 32 | b64enc) | quote }}
  {{- end }}
  databaseUser: {{ "synapse" | b64enc | quote }}
  databasePassword: {{- if $existingSecret }}
    {{ $existingSecret.data.databasePassword }}
  {{- else }}
    {{ (randAlphaNum 16 | b64enc) | quote }}
  {{- end }}
  databaseName: {{ "synapse" | b64enc | quote }}
  databaseHost: {{ "postgres" | b64enc | quote }}
  databasePort: {{ "5432" | b64enc | quote }}