{{- $fullName := include "itl.matrix.synapse.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-cm
data:
  homeserver.yaml: |
    server_name: "matrix.dev.itlusions.com"
    public_baseurl: https://matrix.dev.itlusions.com/
    enable_registration: false
    registration_shared_secret: {{ printf "%%s" (lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" $fullName)).data.registrationSharedSecret | b64dec }}
    database:
      name: sqlite3
      args:
        database: /data/homeserver.db
    listeners:
      - port: 8008
        type: http
        tls: false
        resources: []
        x_forwarded: true
        bind_addresses: ['0.0.0.0']
        paths:
          - path: /_matrix
            handler: matrix
          - path: /_synapse/client
            handler: synapse_admin
    federation_domain_whitelist: null
    log_config: /data/log.config
    media_store_path: /data/media_store
    signing_key_path: "data/matrix.dev.itlusions.com.signing.key"
    report_stats: true
    trusted_key_servers:
      - server_name: "matrix.org"