{{- if .Values.tenant.ingress.matrix.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.tenant.name }}-matrix
  annotations:
    {{- range $key, $value := .Values.tenant.ingress.matrix.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.tenant.ingress.matrix.ingressClassName }}
  tls:
    {{- range .Values.tenant.ingress.matrix.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  rules:
    {{- range .Values.tenant.ingress.matrix.hosts }}
    - host: {{ .host }}
      http:
        paths:
        - path: {{ .path }}
          pathType: {{ .pathType | default "Prefix" }}
          backend:
            service:
              name: {{ $.Values.tenant.servicename }}
              port:
                number: 8008
    {{- end }}
{{- end }}
