{{- $fullName := include "itl.matrix.synapse.name" . -}}
{{- $namespace := .Release.Namespace -}}
{{- $existingSecret := lookup "v1" "Secret" $namespace (printf "%s-secret" $fullName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-wave: "0" # ConfigMap is deployed first
type: Opaque
data:
  registrationSharedSecret: {{- if $existingSecret }}
    {{ $existingSecret.data.registrationSharedSecret }}
  {{- else }}
    {{ (randAlphaNum 32 | b64enc) | quote }}
  {{- end }}
  macook_secret_key: {{- if $existingSecret }}
    {{ $existingSecret.data.macook_secret_key }}
  {{- else }}
    {{ (randAlphaNum 32 | b64enc) | quote }}
  {{- end }}
