{{- $fullName := include "itl.matrix.synapse.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-cm
data:
  homeserver.yaml: |
    server_name: your.domain.com
    public_baseurl: https://your.domain.com/
    enable_registration: false
    registration_shared_secret: "YOUR_SECRET"
    database:
      name: psycopg2
      args:
        user: synapse
        password: synapsepassword
        database: synapse
        host: postgres
        port: 5432
    listeners:
      - port: 8008
        type: http
        tls: false
        resources: []
        x_forwarded: true
        bind_addresses: ['0.0.0.0']
        paths:
          - path: /_matrix
            handler: matrix
          - path: /_synapse/client
            handler: synapse_admin
    # Optional but recommended for federation
    federation_domain_whitelist: null
    log_config: /data/log.config
    media_store_path: /data/media_store
    signing_key_path: /data/signing.key
    report_stats: true
    trusted_key_servers:
      - server_name: "matrix.org"
        verify_keys:
          "ed25519:auto": "yourmatrixorgkeyhere"
        accept_keys_insecurely: false