{{- $fullName := include "itl.matrix.synapse.name" . -}}
{{- $namespace := .Release.Namespace -}}
{{- $secretName := printf "%s-secret" $fullName -}}
{{- $existingSecret := lookup "v1" "Secret" $namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-wave: "0" # Secret is deployed first
type: Opaque
data:
  {{- if $existingSecret }}
  registrationSharedSecret: {{ index $existingSecret.data "registrationSharedSecret" | quote }}
  macaroonSecretKey: {{ index $existingSecret.data "macaroonSecretKey" | default (randAlphaNum 64 | b64enc) | quote }}
  formSecret: {{ index $existingSecret.data "formSecret" | default (randAlphaNum 64 | b64enc) | quote }}
  clientSecret: {{ index $existingSecret.data "clientSecret" | default (randAlphaNum 64 | b64enc) | quote }}
  coturnSharedSecret: {{ index $existingSecret.data "coturnSharedSecret" | default (randAlphaNum 32 | b64enc) | quote }}
  {{- else }}
  registrationSharedSecret: {{ randAlphaNum 64 | b64enc | quote }}
  macaroonSecretKey: {{ randAlphaNum 64 | b64enc | quote }}
  formSecret: {{ randAlphaNum 64 | b64enc | quote }}
  clientSecret: {{ randAlphaNum 64 | b64enc | quote }}
  coturnSharedSecret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}