{{- $fullName := include "itl.matrix.synapse.name" . -}}
{{- $namespace := .Release.Namespace -}}
{{- $secret := lookup "v1" "Secret" $namespace "itl-syn01-secret" | default (dict "data" (dict)) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-cm
  annotations:
    argocd.argoproj.io/sync-wave: "1" # ConfigMap is deployed first
data:
  homeserver.yaml: |
    server_name: "matrix.dev.itlusions.com"
    public_baseurl: "https://matrix.dev.itlusions.com/"
    enable_registration: false
    macaroon_secret_key: "change-me-{{ randAlphaNum 32 }}"
    database:
      name: sqlite3
      args:
        database: /data/homeserver.db
    listeners:
      - port: 8008
        type: http
        tls: false
        resources:
          - names: [client, federation]
            compress: false
        x_forwarded: true
        bind_addresses: ['0.0.0.0']
    media_store_path: /data/media_store
    signing_key_path: "/data/matrix.dev.itlusions.com.signing.key"
    trusted_key_servers:
      - server_name: "matrix.org"
    logging:
      handlers:
        file:
          class: logging.handlers.RotatingFileHandler
          filename: "/data/homeserver.log"
          maxBytes: 104857600
          backupCount: 10
          encoding: utf8