apiVersion: synapse.opdev.io/v1alpha1
kind: Synapse
metadata:
  name: {{ .Values.tenant.name }}-matrix
spec:
  createNewPostgreSQL: {{ .Values.tenant.createNewPostgreSQL | default false }}
  homeserver:
    configMap:
      name: {{ .Values.tenant.name }}-matrix
    values: 
      reportStats: {{ .Values.tenant.homeserver.values.reportStats | default false }}
      serverName: {{ .Values.tenant.homeserver.values.serverName | default "default.server.com" }}