{{- $fullName := include "itl.matrix.synapse.name" . -}}
{{- $namespace := .Release.Namespace -}}
{{- $existingSecret := lookup "v1" "Secret" $namespace (printf "%s-secret" $fullName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-wave: "1" # ConfigMap is deployed first
type: Opaque
data:
  registrationSharedSecret: {{- if and $existingSecret.data.registrationSharedSecret (not (empty $existingSecret.data.registrationSharedSecret)) -}}
    {{ $existingSecret.data.registrationSharedSecret }}
  {{- else -}}
    {{ (randAlphaNum 32 | b64enc) | quote }}
  {{- end }}
  form_secret: {{- if and $existingSecret.data.form_secret (not (empty $existingSecret.data.form_secret)) -}}
    {{ $existingSecret.data.form_secret }}
  {{- else -}}
    {{ (randAlphaNum 32 | b64enc) | quote }}
  {{- end }}
  macaroon_secret_key: {{- if and $existingSecret.data.macaroon_secret_key (not (empty $existingSecret.data.macaroon_secret_key)) -}}
    {{ $existingSecret.data.macaroon_secret_key }}
  {{- else -}}
    {{ (randAlphaNum 32 | b64enc) | quote }}
  {{- end }}