{{- $fullName := include "itl.matrix.synapse.name" . -}}
{{- $namespace := .Release.Namespace -}}
{{- $existingSecret := lookup "v1" "Secret" $namespace (printf "%s-secret" $fullName) -}}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-wave: "0" # ConfigMap is deployed first
type: Opaque
data:
  registrationSharedSecret: {{ (randAlphaNum 32 | b64enc) | quote }}
  macook_secret_key: {{ (randAlphaNum 32 | b64enc) | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "itl.matrix.synapse.name" . }}-secret-02
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  # Registration shared secret
  sharedSecret: {{ .Values.matrix.registration.sharedSecret | default (randAlphaNum 32 | b64enc) }}

  # Database credentials
  postgresqlUsername: {{ .Values.postgresql.username | b64enc }}
  postgresqlPassword: {{ .Values.postgresql.password | b64enc }}
  postgresqlDatabase: {{ .Values.postgresql.database | b64enc }}

  # Email SMTP credentials
  smtpUser: {{ .Values.mail.external.username | b64enc }}
  smtpPass: {{ .Values.mail.external.password | b64enc }}