{{- $fullName := include "itl.matrix.synapse.name" . -}}
{{- $namespace := .Release.Namespace -}}
{{- $tenantName := .Values.tenant.name | default .Release.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-wave: "0" # ConfigMap is deployed first
type: Opaque
data:
  registrationSharedSecret: {{ (printf "%s-registration" $tenantName | sha256sum | trunc 32 | b64enc) | quote }}
  macaroonSecretKey: {{ (printf "%s-macaroon" $tenantName | sha256sum | trunc 32 | b64enc) | quote }}
  formSecret: {{ (printf "%s-form" $tenantName | sha256sum | trunc 32 | b64enc) | quote }}
  clientSecret: {{ (printf "%s-client" $tenantName | sha256sum | trunc 32 | b64enc) | quote }}