apiVersion: synapse.opdev.io/v1alpha1
kind: Synapse
metadata:
  name: itl-syn01-tenant
  annotations:
    argocd.argoproj.io/sync-wave: "3" # Synapse is deployed after ConfigMap
spec:
  homeserver:
    configMap:
      name: itl-syn01-cm
      namespace: {{ .Release.Namespace }}