{{- range .Values.tenants }}
apiVersion: synapse.opdev.io/v1alpha1
kind: Synapse
metadata:
  name: {{ .name }}-matrix
spec:
  createNewPostgreSQL: {{ .createNewPostgreSQL | default false }}
  homeserver:
    values:
      {{- if .homeserver.values.reportStats }}
      reportStats: {{ .homeserver.values.reportStats | default false }}
      {{- else }}
      reportStats: false
      {{- end }}
      {{- if .homeserver.values.serverName }}
      serverName: {{ .homeserver.values.serverName | default "default.server.com" }}
      {{- else }}
      serverName: "default.server.com"
      {{- end }}
      {{- if .homeserver.values.enableRegistration }}
      enableRegistration: {{ .homeserver.values.enableRegistration | default false }}
      {{- else }}
      enableRegistration: false
      {{- end }}

