{{- if not (lookup "synapse.opdev.io/v1alpha1" "Synapse" .Release.Namespace "itl-syn01-tenant") }}
apiVersion: synapse.opdev.io/v1alpha1
kind: Synapse
metadata:
  name: itl-syn01-tenant
  annotations:
spec:
  homeserver:
    configMap:
      name: itl-syn01-cm
      namespace: {{ .Release.Namespace }}
{{- end }}