{{- $fullName := include "itl.matrix.synapse.name" . -}}
{{- $namespace := .Release.Namespace -}}
{{- $secret := lookup "v1" "Secret" $namespace "itl-syn01-secret" | default (dict "data" (dict)) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-cm
  annotations:
    argocd.argoproj.io/sync-wave: "1" # ConfigMap is deployed first
data:
  homeserver.yaml: |
{{ include "itl.matrix.synapse.homeserver" . | indent 4 }}