apiVersion: synapse.opdev.io/v1alpha1
kind: Synapse
metadata:
  name: itl-syn01-tenant
spec:
  homeserver:
    configMap:
      name: itl-syn01-cm
      namespace: {{ .Release.Namespace }}
  macaroon_secret_key: "change-me-{{ randAlphaNum 32 }}"