apiVersion: synapse.opdev.io/v1alpha1
kind: Synapse
metadata:
  name: itl-syn01-tenant
  annotations:
spec:
  homeserver:
    configMap:
      name: itl-syn01-cm
      namespace: {{ .Release.Namespace }}
  serviceAccount:
    name: default