{{- $fullName := include "itl.matrix.synapse.name" . -}}
{{- $namespace := .Release.Namespace -}}
{{- $secret := lookup "v1" "Secret" $namespace "itl-syn01-secret" | default (dict "data" (dict)) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-cm
  annotations:
    argocd.argoproj.io/sync-wave: "1" # ConfigMap is deployed first
data:
  homeserver.yaml: |
    server_name: "matrix.dev.itlusions.com"
    public_baseurl: "https://matrix.dev.itlusions.com/"
    enable_registration: false
    macaroon_secret_key: "change-me-{{ randAlphaNum 32 }}"
    database:
      name: sqlite3
      args:
        database: /data/homeserver.db
    listeners:
      - port: 8008
        type: http
        tls: false
        resources: []
        x_forwarded: true
        bind_addresses: ['0.0.0.0']
        paths:
          - path: /_matrix
            handler: matrix
          - path: /_synapse/client
            handler: synapse_admin
    federation_domain_whitelist: null
    log_config: /data/log.config
    media_store_path: /data/media_store
    signing_key_path: "/data/matrix.dev.itlusions.com.signing.key"
    
    # --- OIDC / Keycloak ---
    sso:
      client_whitelist: []
      whitelisted_sso_clients: []

    oidc_providers:
      - idp_id: keycloak
        idp_name: "Keycloak"
        issuer: "https://sts.itlusions.com/realms/itlusions"
        client_id: "synapse"
        client_secret: "REPLACE_WITH_CLIENT_SECRET"
        scopes: ["openid", "profile", "email"]
        allow_existing_users: true
        user_mapping_provider:
          config:
            localpart_template: "{{ user.preferred_username | lower | replace(' ', '_') }}"
            display_name_template: "{{ user.name or user.preferred_username }}"
            email_template: "{{ user.email }}"
    
    report_stats: true
    trusted_key_servers:
      - server_name: "matrix.org"