{{- range .Values.tenants }}
{{- if .ingress.matrix.enabled }}
{{- $service := (lookup "v1" "Service" .Release.Namespace (printf "%s-matrix" .name)) }}
{{- if $service }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-matrix
  {{- with .ingress.matrix.labels }}
  labels: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .ingress.matrix.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .ingress.matrix.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .ingress.matrix.tls }}
  tls:
    {{- range .ingress.matrix.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .ingress.matrix.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ .name }}-matrix
                port:
                  number: 8008
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
