apiVersion: synapse.opdev.io/v1alpha1
kind: Synapse
metadata:
  name: {{ .Values.tenant.name }}-matrix
spec:
  createNewPostgreSQL: {{ .Values.tenant.createNewPostgreSQL | default false }}
  homeserver:
    values:
      configMap:
        name: {{ .Values.tenant.name }}-matrix-config