apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-homeserver
data:
  homeserver.yaml: |
    server_name: "matrix.example.com"
    public_baseurl: "https://matrix.example.com/"
    registration_shared_secret: "changeme"
    # add other config options...
