apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-sa-role
  namespace: {{ Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-sa-rolebinding
  namespace: {{ Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ Release.Namespace }}
roleRef:
  kind: Role
  name: default-sa-role
  apiGroup: rbac.authorization.k8s.io