name: Release Helm Chart

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Chart version to release'
        required: true
        type: string

env:
  HELM_VERSION: v3.14.0

jobs:
  release:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Add Helm repositories
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo update

      - name: Package Helm Chart
        run: |
          echo "Packaging Helm chart..."
          helm package chart/ --destination ./.cr-release-packages
          echo "✅ Chart packaged successfully"

      - name: Upload Chart to Release
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true

      - name: Verify Release
        run: |
          echo "Verifying release artifacts..."
          ls -la .cr-release-packages/
          echo "✅ Release verification completed"